### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by rossman22590** [mohamedcherifmo/landingpagegpt-public#1]
Can we add a download button to download the code?

**Comment by mohamedcherifmo** [comment]
Added a download button, I presume you meant download as html right?

**Comment by rossman22590** [comment]
thanks!

**Comment by rossman22590** [comment]
how do i solve this? Type error: Property 'html' is missing in type '{}' but required in type 'DownloadButtonProps'.

**Comment by rossman22590** [comment]
nvm solved it with this <DownloadButton html={html}></DownloadButton>
