### ISSUE TITLE
how do i solve this? Type error: Property 'html' is missing in type '{}' but required in type 'DownloadButtonProps'.

### ISSUE THREAD

**Issue by rossman22590** [mohamedcherifmo/landingpagegpt-public#2]
how do i solve this? Type error: Property 'html' is missing in type '{}' but required in type 'DownloadButtonProps'.

_Originally posted by @rossman22590 in https://github.com/mohamedcherifmo/landingpagegpt-public/issues/1#issuecomment-1475064828_

**Comment by mohamedcherifmo** [comment]
This should now be resolved
